### ISSUE TITLE
Missing XCAD upload API

### ISSUE THREAD

**Issue by quer1313** [3ds-cpe-emed/3dxws-dotnet-core-sdk#49]
Is it planned to extend the SDK for creating/uploading xcad files like part or drawing?

**Comment by 3ds-cpe-emed** [comment]
Hi @quer1313 can you please specify the use case that you have in mind?

**Comment by quer1313** [comment]
Hi @3ds-cpe-emed , in the SDK I found GetXCADPart() to load a xcad file from the platform. We also need the other way, to create/upload a xcad file (in our case SOLIDWORKS parts/assemblies/drawing) from the client to the platform.
[/resources/v1/modeler/dsxcad/dsxcad:Part](https://media.3ds.com/support/documentation/developer/Cloud/en/English/CAAXCADWS/dsxcad_v1.htm#/dsxcad:Part/dsxcad:Part)

I tested the Rest API via Postman, but I failed to do this.

**Comment by 3ds-cpe-emed** [comment]
This is currently not supported through the web services. see documentation [here](https://media.3ds.com/support/documentation/developer/Cloud/en/DSDoc.htm?show=CAAXCADWS/CAAXCADWSTaOverview.htm). 
![Screenshot 2022-10-19 123203](https://user-images.githubusercontent.com/94392914/196667533-f1a4d50d-d9f6-4fe1-923b-a6370678cfe7.png)
It might change in the future but for now each CAD provider (Solidworks, Catia, ...) has to provide its own implementation of this. You normally find it in each PowerBy connector (UES, UE5, ...) . There are other tools we have available for partners (e.g. EDAT ) for migration. If you a partner you can get more information about this.?

Alternatively you can try to use the Enterprise IP Exchange Import mechanism - [here](https://media.3ds.com/support/documentation/developer/Cloud/en/DSDoc.htm?show=CAAExchangeWS/CAAExchangeImportOverview.htm)  - this is not in scope for the SDK currently.
